apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ctbe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ctbe
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ctbe
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ctbe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ctbe
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jczn-tenant/rhtap-demo-app/hacbs-test-project-ctbe@sha256:f1f250827a885c8a8378dc858fa1ebd4de9c64c149cd5bd82706d810fb2db8ad
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
